
import { Fenix } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header/Header";
import ParticlesBG from "@/app/components/particles/ParticlesBG";
import Footer from "@/app/components/footer/Footer";
import {LanguageProvider} from "@/app/LanguageContext";
import ScrollToTopButton from "@/app/components/scrolltotop/ScrollToTopButton";




const fenix = Fenix({ subsets: ["latin"], display: "swap", weight: "400" });

export const metadata = {
  title: "Railtok recruitment",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {


    return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <body className={`${fenix.className} 'scroll-smooth`}>
      <LanguageProvider>
      <Header />

      <main className="pt-[60px] lg:pt-[85px]">
        <ScrollToTopButton/>
          <ParticlesBG/>
          {children}
      </main>
      <Footer/>
      </LanguageProvider>
      </body>
    </html>
  );
}
